"use client"

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/6BUASTIxnbn
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { useState } from "react"

export function AddUserForm() {

  const [name, setName] = useState('');
  const [email, setEmail] = useState('');


  const [accountCreatedSuccessfully, setAccountCreatedSuccessfully] = useState(false);





  return (
    <div key="1" className="space-y-6">
      <div className="space-y-2 text-center">
        <h2 className="text-3xl font-bold">Create an account</h2>
        <p className="text-gray-500 dark:text-gray-400">Enter your information to create an account</p>
      </div>
      <div className="space-y-4">
        <div className="space-y-2">
          <Label htmlFor="name">Name</Label>
          <Input id="name" placeholder="Name" value={name} onChange={(e) => setName(e.target.value)}/>
        </div>
        <div className="space-y-2">
          <Label htmlFor="email">Email</Label>
          <Input id="email" placeholder="Email" type="email" value={email} onChange={(e) => setEmail(e.target.value)}/>
        </div>
        <Button className="w-full" type="submit" onClick={
          async () => {
            if (!name || !email) {
              console.log('Please fill in all the fields');
              return;
            }

            
          }
        }>
          Sign Up
        </Button>

        {accountCreatedSuccessfully && (
          <div className="text-green-500 dark:text-green-400">
            Account created successfully
          </div>
        )}

      </div>
    </div>
  )
}
